# Generated by Django 4.0.4 on 2022-05-08 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=255)),
                ('titleSearch', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('title', 'year')},
            },
        ),
    ]
